package badsmells;

/*
 * Smell: Divergent Change
 *
 * Original: One class handled report formatting, SQL generation, and CSV export —
 * three different reasons to change crammed into one place.
 * Fix: Extracted three focused classes, each with one responsibility.
 *
 * Refactorings applied: Extract Class, Move
 */
public class DivergentChangeExample {

    static class ExamReportFormatter {
        private final String title = "Exam Results";
        private final String footer = "Generated by registrar office";

        public String formatStudentReport(String name, int score) {
            return title + "\n" + name + ": " + score + "\n" + footer;
        }
    }

    static class ExamSqlBuilder {
        private final String tableName = "exam_results";
        private final String databaseUrl = "jdbc:mysql://localhost:3306/school";

        public String buildSqlInsert(String name, int score) {
            return "/* " + databaseUrl + " */ INSERT INTO " + tableName
                 + "(name, score) VALUES ('" + name + "', " + score + ")";
        }
    }

    static class ExamCsvExporter {
        private final String separator = ",";
        private final boolean includeHeader = true;

        public String exportCsv(String name, int score) {
            String row = name + separator + score;
            return includeHeader ? "name" + separator + "score\n" + row : row;
        }
    }

    public void clientCode() {
        ExamReportFormatter formatter = new ExamReportFormatter();
        ExamSqlBuilder sqlBuilder = new ExamSqlBuilder();
        ExamCsvExporter csvExporter = new ExamCsvExporter();

        System.out.println(formatter.formatStudentReport("Nino", 95));
        System.out.println(sqlBuilder.buildSqlInsert("Nino", 95));
        System.out.println(csvExporter.exportCsv("Nino", 95));
    }
}
